name: Deploy VitePress Site

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 版本
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装依赖并构建项目
      - name: Install and Build
        run: |
          npm ci  # 使用 npm ci 确保版本一致
          npm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist  # VitePress 构建输出目录
